[[session]]
name = "tmux config"
path = "~/.config/tmux"
startup_command = "vi -c ':Pick files'"
# preview_command = "bat --color=always ~/c/dotfiles/.config/tmux/tmux.conf"

[[session]]
name = "nvim config"
path = "~/.config/nvim"
startup_command = "vi -c ':Pick files'"
# preview_command = "bat --color=always ~/c/dotfiles/.config/tmux/tmux.conf"

[[session]]
name = "COSC2802"
path = "~/repos/rmit/COSC2802"
startup_command = "vi -c ':Pick files'"
# preview_command = "bat --color=always ~/c/dotfiles/.config/tmux/tmux.conf"

[[session]]
name = "COSC2804"
path = "~/repos/rmit/COSC2804"
startup_command = "vi -c ':Pick files'"
preview_command = "ls -h"


[[session]]
name = "curas-server"
path = "~/repos/curas/curas-server"
startup_command = "vi -c ':Pick files'"
# preview_command = "bat --color=always ~/c/dotfiles/.config/tmux/tmux.conf"

[[session]]
name = "curas-web"
path = "~/repos/curas/curas-web"
startup_command = "vi -c ':Pick files'"
# preview_command = "bat --color=always ~/c/dotfiles/.config/tmux/tmux.conf"
